export const stats = {
  totalCustomers: { value: 58234, change: 6.2, weeklyIncrease: 874 },
  newCustomers: { value: 895, change: 15.1, weeklyIncrease: 124 },
  avgOrderValue: { value: 98.45, change: 1.8, weeklyIncrease: 3.4 },
  customerSatisfaction: { value: 4.7, change: 1.9 },
};

export const customers = [
  {
    id: "CUST-101",
    name: "Rajesh Kumar",
    contact: "rajesh.kumar@gmail.com",
    phone: "+91 98765-43210",
    marketplace: "AgriMart",
    orders: 58,
    totalSpent: "$1,234",
    status: "Active",
  },
  {
    id: "CUST-102",
    name: "Anita Sharma",
    contact: "anita.sharma@gmail.com",
    phone: "+91 87654-32109",
    marketplace: "FarmTools",
    orders: 46,
    totalSpent: "$987",
    status: "Active",
  },
  {
    id: "CUST-103",
    name: "Vikram Singh",
    contact: "vikram.singh@gmail.com",
    phone: "+91 76543-21098",
    marketplace: "AgroStore",
    orders: 72,
    totalSpent: "$1,540",
    status: "Active",
  },
  {
    id: "CUST-104",
    name: "Priya Desai",
    contact: "priya.desai@gmail.com",
    phone: "+91 65432-10987",
    marketplace: "AgriMart",
    orders: 38,
    totalSpent: "$712",
    status: "Inactive",
  },
  {
    id: "CUST-105",
    name: "Suresh Patel",
    contact: "suresh.patel@gmail.com",
    phone: "+91 54321-09876",
    marketplace: "FarmTools",
    orders: 61,
    totalSpent: "$1,025",
    status: "Blocked",
  },
  {
    id: "CUST-106",
    name: "Meera Joshi",
    contact: "meera.joshi@gmail.com",
    phone: "+91 43210-98765",
    marketplace: "AgroStore",
    orders: 54,
    totalSpent: "$899",
    status: "Active",
  },
  {
    id: "CUST-107",
    name: "Rahul Mehta",
    contact: "rahul.mehta@gmail.com",
    phone: "+91 32109-87654",
    marketplace: "AgriMart",
    orders: 67,
    totalSpent: "$1,432",
    status: "Active",
  },
  {
    id: "CUST-108",
    name: "Kavita Reddy",
    contact: "kavita.reddy@gmail.com",
    phone: "+91 21098-76543",
    marketplace: "FarmTools",
    orders: 49,
    totalSpent: "$1,112",
    status: "Blocked",
  },
  {
    id: "CUST-109",
    name: "Ajay Nair",
    contact: "ajay.nair@gmail.com",
    phone: "+91 10987-65432",
    marketplace: "AgroStore",
    orders: 55,
    totalSpent: "$1,287",
    status: "Active",
  },
  {
    id: "CUST-110",
    name: "Sunita Rao",
    contact: "sunita.rao@gmail.com",
    phone: "+91 09876-54321",
    marketplace: "AgriMart",
    orders: 42,
    totalSpent: "$765",
    status: "Inactive",
  },
];
